version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  gymatedb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  cachedb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  identityserver.api:
    image: ${DOCKER_REGISTRY-}identityserverapi
    build:
      context: .
      dockerfile: Services\IdentityServer\IdentityServer.Api\Dockerfile

  exercises.api:
    image: ${DOCKER_REGISTRY-}exercisesapi
    build:
      context: .
      dockerfile: Services\Exercises\Exercises.Api\Dockerfile

  workout.api:
    image: ${DOCKER_REGISTRY-}workoutapi
    build:
      context: .
      dockerfile: Services\Workout\Workouts.Api\Dockerfile

volumes:
  portainer_data:
  elasticsearch-data: