version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  gymatedb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  cachedb:
    image: redis:alpine

  exercises.api:
    image: ${DOCKER_REGISTRY-}exercisesapi
    build:
      context: .
      dockerfile: Services\Exercises\Exercises.Api\Dockerfile

volumes:
  portainer_data: