version: '3.4'

services:
  exercisedb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  exercises.api:
    image: ${DOCKER_REGISTRY-}exercisesapi
    build:
      context: .
      dockerfile: Services\Exercises\Exercises.Api\Dockerfile
