version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  gymatedb:
    container_name: gymatedb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  cachedb:
    container_name: cachedb
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Urls:IdentityServerApi=http://identityserver.api:80"
    depends_on:
      - exercises.api
    ports:
      - "8010:80"

  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=gymatedb;Database=GymateIdentityDb;User Id=sa;Password=SwN12345678;"
      - "ConnectionStrings:ElasticSearchConnection=http://elasticsearch:9200"
    depends_on:
      - gymatedb
      - elasticsearch
    ports:
      - "8050:80"

  exercises.api:
    container_name: exercises.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=gymatedb;Database=GymateExerciseDb;User Id=sa;Password=SwN12345678;"
      - "ConnectionStrings:ElasticSearchConnection=http://elasticsearch:9200"
      - "ConnectionStrings:RedisConnection=cachedb:6379"
      - "Urls:IdentityServerApi=http://identityserver.api:80"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - gymatedb
      - cachedb
      - rabbitmq
      - elasticsearch
    ports:
      - "8000:80"

  workout.api:
    container_name: workout.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=gymatedb;Database=GymateWorkoutDb;User Id=sa;Password=SwN12345678;"
      - "ConnectionStrings:ElasticSearchConnection=http://elasticsearch:9200"
      - "Urls:IdentityServerApi=http://identityserver.api:80"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - gymatedb
      - rabbitmq
      - elasticsearch
    ports:
      - "8001:80"

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Exercise Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://exercises.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Workout Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://workout.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Aggregator Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://aggregator.api/hc
    ports:
      - "5000:80"

  gymate.aggregator:
    container_name: aggregator.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ElasticSearchConnection=http://elasticsearch:9200"
      - "Urls:Exercise=http://exercises.api"
      - "Urls:Workout=http://workout.api"
      - "Urls:IdentityServerApi=http://identityserver.api:80"
    depends_on:
      - identityserver.api
      - exercises.api
      - workout.api
      - elasticsearch
    ports:
      - "5287:80"

